"""initial

Revision ID: f455cd7f7b74
Revises: 
Create Date: 2026-03-13 10:59:34.014090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f455cd7f7b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=25), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Text', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
